program main
  USE mod_parameters
  USE mod_VERIF
  USE mod_VOI
  USE mod_CONNEC_COO
  Implicit None

  PRINT*,'DEFINE:', STCO,STCN,NBPELE,NBPEDG
  CALL RD_MF_CONNEC_COO(MESH_FILE,DIM,NV,NE,NT,T1CO,T1CN,T1ED,T1ED_L,T2D)

  CALL QK_INFO_CNCO(T1CN, T1CO, MESH_QK_CNCO)
  CALL BUILD_HEAD_VOI_CN(T1CN,head,voi)
  FCRTL = WR_verif_CNCO(MESH_QK_CNCO)
  DEALLOCATE(head, voi)

  CALL QK_INFO_T2DCO(T2D, T1CO, MESH_QK_T2DCO)
  CALL  BUILD_HEAD_VOI_T2D(T2D,head,voi)
  FCRTL = WR_verif_T2DCO(MESH_QK_T2DCO)
  DEALLOCATE(head, voi)

  DEALLOCATE(T2D, T1CO, T1CN, T1ED, T1ED_L)

end program main
